/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PTYSessionInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PTYSessionInfo{}

// PTYSessionInfo struct for PTYSessionInfo
type PTYSessionInfo struct {
	// The unique identifier for the PTY session
	Id string `json:"id"`
	// The command running in the PTY session
	Command []string `json:"command"`
	// Working directory of the PTY session
	WorkDir string `json:"workDir"`
	// Environment variables for the PTY session
	Env map[string]interface{} `json:"env"`
	// Number of terminal columns
	Cols float32 `json:"cols"`
	// Number of terminal rows
	Rows float32 `json:"rows"`
	// When the PTY session was created
	CreatedAt string `json:"createdAt"`
	// Whether the PTY session is currently active
	Active bool `json:"active"`
}

type _PTYSessionInfo PTYSessionInfo

// NewPTYSessionInfo instantiates a new PTYSessionInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPTYSessionInfo(id string, command []string, workDir string, env map[string]interface{}, cols float32, rows float32, createdAt string, active bool) *PTYSessionInfo {
	this := PTYSessionInfo{}
	this.Id = id
	this.Command = command
	this.WorkDir = workDir
	this.Env = env
	this.Cols = cols
	this.Rows = rows
	this.CreatedAt = createdAt
	this.Active = active
	return &this
}

// NewPTYSessionInfoWithDefaults instantiates a new PTYSessionInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPTYSessionInfoWithDefaults() *PTYSessionInfo {
	this := PTYSessionInfo{}
	return &this
}

// GetId returns the Id field value
func (o *PTYSessionInfo) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PTYSessionInfo) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PTYSessionInfo) SetId(v string) {
	o.Id = v
}

// GetCommand returns the Command field value
func (o *PTYSessionInfo) GetCommand() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Command
}

// GetCommandOk returns a tuple with the Command field value
// and a boolean to check if the value has been set.
func (o *PTYSessionInfo) GetCommandOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Command, true
}

// SetCommand sets field value
func (o *PTYSessionInfo) SetCommand(v []string) {
	o.Command = v
}

// GetWorkDir returns the WorkDir field value
func (o *PTYSessionInfo) GetWorkDir() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkDir
}

// GetWorkDirOk returns a tuple with the WorkDir field value
// and a boolean to check if the value has been set.
func (o *PTYSessionInfo) GetWorkDirOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkDir, true
}

// SetWorkDir sets field value
func (o *PTYSessionInfo) SetWorkDir(v string) {
	o.WorkDir = v
}

// GetEnv returns the Env field value
func (o *PTYSessionInfo) GetEnv() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Env
}

// GetEnvOk returns a tuple with the Env field value
// and a boolean to check if the value has been set.
func (o *PTYSessionInfo) GetEnvOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Env, true
}

// SetEnv sets field value
func (o *PTYSessionInfo) SetEnv(v map[string]interface{}) {
	o.Env = v
}

// GetCols returns the Cols field value
func (o *PTYSessionInfo) GetCols() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Cols
}

// GetColsOk returns a tuple with the Cols field value
// and a boolean to check if the value has been set.
func (o *PTYSessionInfo) GetColsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cols, true
}

// SetCols sets field value
func (o *PTYSessionInfo) SetCols(v float32) {
	o.Cols = v
}

// GetRows returns the Rows field value
func (o *PTYSessionInfo) GetRows() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Rows
}

// GetRowsOk returns a tuple with the Rows field value
// and a boolean to check if the value has been set.
func (o *PTYSessionInfo) GetRowsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rows, true
}

// SetRows sets field value
func (o *PTYSessionInfo) SetRows(v float32) {
	o.Rows = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *PTYSessionInfo) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *PTYSessionInfo) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *PTYSessionInfo) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetActive returns the Active field value
func (o *PTYSessionInfo) GetActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Active
}

// GetActiveOk returns a tuple with the Active field value
// and a boolean to check if the value has been set.
func (o *PTYSessionInfo) GetActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Active, true
}

// SetActive sets field value
func (o *PTYSessionInfo) SetActive(v bool) {
	o.Active = v
}

func (o PTYSessionInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PTYSessionInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["command"] = o.Command
	toSerialize["workDir"] = o.WorkDir
	toSerialize["env"] = o.Env
	toSerialize["cols"] = o.Cols
	toSerialize["rows"] = o.Rows
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["active"] = o.Active
	return toSerialize, nil
}

func (o *PTYSessionInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"command",
		"workDir",
		"env",
		"cols",
		"rows",
		"createdAt",
		"active",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPTYSessionInfo := _PTYSessionInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPTYSessionInfo)

	if err != nil {
		return err
	}

	*o = PTYSessionInfo(varPTYSessionInfo)

	return err
}

type NullablePTYSessionInfo struct {
	value *PTYSessionInfo
	isSet bool
}

func (v NullablePTYSessionInfo) Get() *PTYSessionInfo {
	return v.value
}

func (v *NullablePTYSessionInfo) Set(val *PTYSessionInfo) {
	v.value = val
	v.isSet = true
}

func (v NullablePTYSessionInfo) IsSet() bool {
	return v.isSet
}

func (v *NullablePTYSessionInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePTYSessionInfo(val *PTYSessionInfo) *NullablePTYSessionInfo {
	return &NullablePTYSessionInfo{value: val, isSet: true}
}

func (v NullablePTYSessionInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePTYSessionInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


