/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PTYCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PTYCreateRequest{}

// PTYCreateRequest struct for PTYCreateRequest
type PTYCreateRequest struct {
	// The unique identifier for the PTY session
	Id string `json:"id"`
	// The command to run in the PTY session
	Command []string `json:"command"`
	// Working directory for the PTY session
	WorkDir *string `json:"workDir,omitempty"`
	// Environment variables for the PTY session
	Env map[string]interface{} `json:"env,omitempty"`
	// Number of terminal columns
	Cols *float32 `json:"cols,omitempty"`
	// Number of terminal rows
	Rows *float32 `json:"rows,omitempty"`
}

type _PTYCreateRequest PTYCreateRequest

// NewPTYCreateRequest instantiates a new PTYCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPTYCreateRequest(id string, command []string) *PTYCreateRequest {
	this := PTYCreateRequest{}
	this.Id = id
	this.Command = command
	var cols float32 = 80
	this.Cols = &cols
	var rows float32 = 24
	this.Rows = &rows
	return &this
}

// NewPTYCreateRequestWithDefaults instantiates a new PTYCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPTYCreateRequestWithDefaults() *PTYCreateRequest {
	this := PTYCreateRequest{}
	var cols float32 = 80
	this.Cols = &cols
	var rows float32 = 24
	this.Rows = &rows
	return &this
}

// GetId returns the Id field value
func (o *PTYCreateRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PTYCreateRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PTYCreateRequest) SetId(v string) {
	o.Id = v
}

// GetCommand returns the Command field value
func (o *PTYCreateRequest) GetCommand() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Command
}

// GetCommandOk returns a tuple with the Command field value
// and a boolean to check if the value has been set.
func (o *PTYCreateRequest) GetCommandOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Command, true
}

// SetCommand sets field value
func (o *PTYCreateRequest) SetCommand(v []string) {
	o.Command = v
}

// GetWorkDir returns the WorkDir field value if set, zero value otherwise.
func (o *PTYCreateRequest) GetWorkDir() string {
	if o == nil || IsNil(o.WorkDir) {
		var ret string
		return ret
	}
	return *o.WorkDir
}

// GetWorkDirOk returns a tuple with the WorkDir field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PTYCreateRequest) GetWorkDirOk() (*string, bool) {
	if o == nil || IsNil(o.WorkDir) {
		return nil, false
	}
	return o.WorkDir, true
}

// HasWorkDir returns a boolean if a field has been set.
func (o *PTYCreateRequest) HasWorkDir() bool {
	if o != nil && !IsNil(o.WorkDir) {
		return true
	}

	return false
}

// SetWorkDir gets a reference to the given string and assigns it to the WorkDir field.
func (o *PTYCreateRequest) SetWorkDir(v string) {
	o.WorkDir = &v
}

// GetEnv returns the Env field value if set, zero value otherwise.
func (o *PTYCreateRequest) GetEnv() map[string]interface{} {
	if o == nil || IsNil(o.Env) {
		var ret map[string]interface{}
		return ret
	}
	return o.Env
}

// GetEnvOk returns a tuple with the Env field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PTYCreateRequest) GetEnvOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Env) {
		return map[string]interface{}{}, false
	}
	return o.Env, true
}

// HasEnv returns a boolean if a field has been set.
func (o *PTYCreateRequest) HasEnv() bool {
	if o != nil && !IsNil(o.Env) {
		return true
	}

	return false
}

// SetEnv gets a reference to the given map[string]interface{} and assigns it to the Env field.
func (o *PTYCreateRequest) SetEnv(v map[string]interface{}) {
	o.Env = v
}

// GetCols returns the Cols field value if set, zero value otherwise.
func (o *PTYCreateRequest) GetCols() float32 {
	if o == nil || IsNil(o.Cols) {
		var ret float32
		return ret
	}
	return *o.Cols
}

// GetColsOk returns a tuple with the Cols field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PTYCreateRequest) GetColsOk() (*float32, bool) {
	if o == nil || IsNil(o.Cols) {
		return nil, false
	}
	return o.Cols, true
}

// HasCols returns a boolean if a field has been set.
func (o *PTYCreateRequest) HasCols() bool {
	if o != nil && !IsNil(o.Cols) {
		return true
	}

	return false
}

// SetCols gets a reference to the given float32 and assigns it to the Cols field.
func (o *PTYCreateRequest) SetCols(v float32) {
	o.Cols = &v
}

// GetRows returns the Rows field value if set, zero value otherwise.
func (o *PTYCreateRequest) GetRows() float32 {
	if o == nil || IsNil(o.Rows) {
		var ret float32
		return ret
	}
	return *o.Rows
}

// GetRowsOk returns a tuple with the Rows field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PTYCreateRequest) GetRowsOk() (*float32, bool) {
	if o == nil || IsNil(o.Rows) {
		return nil, false
	}
	return o.Rows, true
}

// HasRows returns a boolean if a field has been set.
func (o *PTYCreateRequest) HasRows() bool {
	if o != nil && !IsNil(o.Rows) {
		return true
	}

	return false
}

// SetRows gets a reference to the given float32 and assigns it to the Rows field.
func (o *PTYCreateRequest) SetRows(v float32) {
	o.Rows = &v
}

func (o PTYCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PTYCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["command"] = o.Command
	if !IsNil(o.WorkDir) {
		toSerialize["workDir"] = o.WorkDir
	}
	if !IsNil(o.Env) {
		toSerialize["env"] = o.Env
	}
	if !IsNil(o.Cols) {
		toSerialize["cols"] = o.Cols
	}
	if !IsNil(o.Rows) {
		toSerialize["rows"] = o.Rows
	}
	return toSerialize, nil
}

func (o *PTYCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"command",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPTYCreateRequest := _PTYCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPTYCreateRequest)

	if err != nil {
		return err
	}

	*o = PTYCreateRequest(varPTYCreateRequest)

	return err
}

type NullablePTYCreateRequest struct {
	value *PTYCreateRequest
	isSet bool
}

func (v NullablePTYCreateRequest) Get() *PTYCreateRequest {
	return v.value
}

func (v *NullablePTYCreateRequest) Set(val *PTYCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePTYCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePTYCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePTYCreateRequest(val *PTYCreateRequest) *NullablePTYCreateRequest {
	return &NullablePTYCreateRequest{value: val, isSet: true}
}

func (v NullablePTYCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePTYCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


