/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PTYListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PTYListResponse{}

// PTYListResponse struct for PTYListResponse
type PTYListResponse struct {
	// List of active PTY sessions
	Sessions []PTYSessionInfo `json:"sessions"`
}

type _PTYListResponse PTYListResponse

// NewPTYListResponse instantiates a new PTYListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPTYListResponse(sessions []PTYSessionInfo) *PTYListResponse {
	this := PTYListResponse{}
	this.Sessions = sessions
	return &this
}

// NewPTYListResponseWithDefaults instantiates a new PTYListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPTYListResponseWithDefaults() *PTYListResponse {
	this := PTYListResponse{}
	return &this
}

// GetSessions returns the Sessions field value
func (o *PTYListResponse) GetSessions() []PTYSessionInfo {
	if o == nil {
		var ret []PTYSessionInfo
		return ret
	}

	return o.Sessions
}

// GetSessionsOk returns a tuple with the Sessions field value
// and a boolean to check if the value has been set.
func (o *PTYListResponse) GetSessionsOk() ([]PTYSessionInfo, bool) {
	if o == nil {
		return nil, false
	}
	return o.Sessions, true
}

// SetSessions sets field value
func (o *PTYListResponse) SetSessions(v []PTYSessionInfo) {
	o.Sessions = v
}

func (o PTYListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PTYListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sessions"] = o.Sessions
	return toSerialize, nil
}

func (o *PTYListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sessions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPTYListResponse := _PTYListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPTYListResponse)

	if err != nil {
		return err
	}

	*o = PTYListResponse(varPTYListResponse)

	return err
}

type NullablePTYListResponse struct {
	value *PTYListResponse
	isSet bool
}

func (v NullablePTYListResponse) Get() *PTYListResponse {
	return v.value
}

func (v *NullablePTYListResponse) Set(val *PTYListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePTYListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePTYListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePTYListResponse(val *PTYListResponse) *NullablePTYListResponse {
	return &NullablePTYListResponse{value: val, isSet: true}
}

func (v NullablePTYListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePTYListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


