/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PTYCreateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PTYCreateResponse{}

// PTYCreateResponse struct for PTYCreateResponse
type PTYCreateResponse struct {
	// The unique identifier for the created PTY session
	SessionId string `json:"sessionId"`
}

type _PTYCreateResponse PTYCreateResponse

// NewPTYCreateResponse instantiates a new PTYCreateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPTYCreateResponse(sessionId string) *PTYCreateResponse {
	this := PTYCreateResponse{}
	this.SessionId = sessionId
	return &this
}

// NewPTYCreateResponseWithDefaults instantiates a new PTYCreateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPTYCreateResponseWithDefaults() *PTYCreateResponse {
	this := PTYCreateResponse{}
	return &this
}

// GetSessionId returns the SessionId field value
func (o *PTYCreateResponse) GetSessionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value
// and a boolean to check if the value has been set.
func (o *PTYCreateResponse) GetSessionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionId, true
}

// SetSessionId sets field value
func (o *PTYCreateResponse) SetSessionId(v string) {
	o.SessionId = v
}

func (o PTYCreateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PTYCreateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sessionId"] = o.SessionId
	return toSerialize, nil
}

func (o *PTYCreateResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sessionId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPTYCreateResponse := _PTYCreateResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPTYCreateResponse)

	if err != nil {
		return err
	}

	*o = PTYCreateResponse(varPTYCreateResponse)

	return err
}

type NullablePTYCreateResponse struct {
	value *PTYCreateResponse
	isSet bool
}

func (v NullablePTYCreateResponse) Get() *PTYCreateResponse {
	return v.value
}

func (v *NullablePTYCreateResponse) Set(val *PTYCreateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePTYCreateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePTYCreateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePTYCreateResponse(val *PTYCreateResponse) *NullablePTYCreateResponse {
	return &NullablePTYCreateResponse{value: val, isSet: true}
}

func (v NullablePTYCreateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePTYCreateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


