/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PTYResizeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PTYResizeRequest{}

// PTYResizeRequest struct for PTYResizeRequest
type PTYResizeRequest struct {
	// Number of terminal columns
	Cols float32 `json:"cols"`
	// Number of terminal rows
	Rows float32 `json:"rows"`
}

type _PTYResizeRequest PTYResizeRequest

// NewPTYResizeRequest instantiates a new PTYResizeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPTYResizeRequest(cols float32, rows float32) *PTYResizeRequest {
	this := PTYResizeRequest{}
	this.Cols = cols
	this.Rows = rows
	return &this
}

// NewPTYResizeRequestWithDefaults instantiates a new PTYResizeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPTYResizeRequestWithDefaults() *PTYResizeRequest {
	this := PTYResizeRequest{}
	return &this
}

// GetCols returns the Cols field value
func (o *PTYResizeRequest) GetCols() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Cols
}

// GetColsOk returns a tuple with the Cols field value
// and a boolean to check if the value has been set.
func (o *PTYResizeRequest) GetColsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cols, true
}

// SetCols sets field value
func (o *PTYResizeRequest) SetCols(v float32) {
	o.Cols = v
}

// GetRows returns the Rows field value
func (o *PTYResizeRequest) GetRows() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Rows
}

// GetRowsOk returns a tuple with the Rows field value
// and a boolean to check if the value has been set.
func (o *PTYResizeRequest) GetRowsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rows, true
}

// SetRows sets field value
func (o *PTYResizeRequest) SetRows(v float32) {
	o.Rows = v
}

func (o PTYResizeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PTYResizeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cols"] = o.Cols
	toSerialize["rows"] = o.Rows
	return toSerialize, nil
}

func (o *PTYResizeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cols",
		"rows",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPTYResizeRequest := _PTYResizeRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPTYResizeRequest)

	if err != nil {
		return err
	}

	*o = PTYResizeRequest(varPTYResizeRequest)

	return err
}

type NullablePTYResizeRequest struct {
	value *PTYResizeRequest
	isSet bool
}

func (v NullablePTYResizeRequest) Get() *PTYResizeRequest {
	return v.value
}

func (v *NullablePTYResizeRequest) Set(val *PTYResizeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePTYResizeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePTYResizeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePTYResizeRequest(val *PTYResizeRequest) *NullablePTYResizeRequest {
	return &NullablePTYResizeRequest{value: val, isSet: true}
}

func (v NullablePTYResizeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePTYResizeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


